### ISSUE TITLE
Format of user_roles

### ISSUE THREAD

**Issue by asalic** [indigo-dc/alien4cloud#10]
We need an examples of how the list of roles should be defined, either YAML array, or a concatenated String. Furthermore, we need the actual string values of the roles that can be added in the array.

**Comment by jose-sanchezm** [comment]
Please, have a look at pull request https://github.com/indigo-dc/alien4cloud/pull/11 if it's enough, I will merge it.

**Comment by asalic** [comment]
Task done, I'm closing it
